name: Generate Contribution Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  
  # Manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks repo under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Debugging to check variables and if the username is valid
      - name: Debugging
        run: |
          echo "Github username: EthicalGopher"
          echo "Checking if dist directory exists..."
          ls -alh dist || echo "dist directory not found"

      # Generates the snake without specifying outputs explicitly
      - name: Generate snake GIF
        uses: Platane/snk@v2.0.0
        id: snake-gif
        with:
          github_user_name: EthicalGopher
          
      # Show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
